export const HOSTNAME = 'http://localhost:8086';
export const HOSTNAME_DEFAULT = 'http://localhost:8080';
export const JWT_NAME = 'jwt';
export const ROLE = { 
  ROLE_ADMIN:'ADMIN',
  ROLE_STAFF: 'STAFF',
  ROLE_USER: 'USER'
};
export const STATUS_BILL = {
  REQUESTED: 'REQUESTED',
  APPROVED: 'APPROVED',
  UNAPPROVED: 'UNAPPROVED',
  CANCELED: 'CANCELED',
  DELIVERY: 'DELIVERY',
  COMPLETED: 'COMPLETED'
};
export const PAGE_SIZE_PRODUCT = 3;
export const PAGE_SIZE_STAFF = 1;
export const PAGE_SIZE_STORE = 5;
export const ITEM_NUMBER_PAGINATION = 5;
export const LIMIT_NOTIFICATION_SHOW = 5;
export const COMPONENT_NAME_LOGIN = 'LOGIN';
export const COMPONENT_NAME_DASHBOARD = 'DASHBOARD';
export const COMPONENT_NAME_STATISTICS = 'STATISTICS';
export const COMPONENT_NAME_SIDE_BAR = 'SIDE_BAR';
export const COMPONENT_NAME_NAVBAR = 'NAVBAR';
export const COMPONENT_NAME_ERROR = 'ERROR';
export const COMPONENT_NAME_PRODUCTS = 'PRODUCTS';
export const COMPONENT_NAME_SECTION_HEADER = 'SECTION_HEADER';
export const COMPONENT_NAME_TABLE_PRODUCTS = 'TABLE_PRODUCTS';
export const COMPONENT_NAME_ADD_PRODUCT = 'ADD_PRODUCT';
export const COMPONENT_NAME_ACTION_PRODUCT = 'ACTION_PRODUCT';
export const COMPONENT_NAME_PRODUCT_INFO = 'PRODUCT_INFO';
export const COMPONENT_NAME_BASIC_PRODUCT_INFO = 'BASIC_PRODUCT_INFO';
export const COMPONENT_NAME_STAFFS = 'STAFFS';
export const COMPONENT_NAME_ADD_STAFF= 'ADD_STAFF';
export const COMPONENT_NAME_ACTION_STAFF = 'ACTION_STAFF';
export const COMPONENT_NAME_STAFF_INFO = 'STAFF_INFO';
export const COMPONENT_NAME_TABLE_STAFFS = 'TABLE_STAFFS';
export const COMPONENT_NAME_STORES = 'STORES';
export const COMPONENT_NAME_TABLE_STORES = 'TABLE_STORES';
export const COMPONENT_NAME_BASIC_STORE_INFO = 'BASIC_STORE_INFO';
export const COMPONENT_NAME_ACTION_STORE = 'ACTION_STORE';
export const COMPONENT_NAME_SPINNER = 'SPINNER';
export const COMPONENT_NAME_ALERT_POPUP = 'ALERT_POPUP';
export const COMPONENT_NAME_VIEW_IMAGE = 'VIEW_IMAGE';
export const COMPONENT_NAME_PAGINATION = 'PAGINATION';
export const COMPONENT_NAME_PROFILE = 'PROFILE';
export const COMPONENT_NAME_PERSONAL_INFO = 'PERSONAL_INFO';
export const COMPONENT_NAME_CHANGE_PASSWORD = 'CHANGE_PASSWORD';