export const MUTATION_LOGIN = 'LOGIN';
export const AUTHENTICATED = 'AUTHENTICATED';
export const MUTATION_NAME_LOGOUT = 'LOGOUT';
export const MUTATION_NAME_SET_PRODUCTS = 'SET_PRODUCTS';
export const MUTATION_NAME_SET_TOTAL_PAGE_PRODUCT = 'SET_TOTAL_PAGE_PRODUCT';
export const MUTATION_NAME_SET_CATEGORIES = 'SET_CATEGORIES';
export const MUTATION_NAME_SET_STORES = 'SET_STORES';
export const MUTATION_NAME_RESET_MENU = 'RESET_MENU';